# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  smoke-test:
    name: "Test"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install zipfile36
    - name: Restore NuGet packages
      run: |
        cd Magitek
        nuget restore Magitek.sln
    - name: Build solution
      run: |
        cd Magitek
        msbuild Magitek.sln /p:Configuration=Release
    - name: Generate Version.txt
      run: echo "test-${{ github.run_number }}" > ./Magitek/bin/release/Version.txt

    - name: Create Magitek.zip
      run: |
        python -c "
        import os
        import zipfile

        # Define paths
        zip_path = './Magitek/bin/release/Magitek.zip'

        # Step 1: Create initial zip archive with the specified files
        with zipfile.ZipFile(zip_path, 'w') as zipf:
            zipf.write('./Magitek/bin/release/Magitek.dll', arcname='Magitek.dll')
            zipf.write('./Magitek/bin/release/Magitek.pdb', arcname='Magitek.pdb')
            zipf.write('./Magitek/bin/release/zh-CN/Magitek.resources.dll', arcname='zh-CN/Magitek.resources.dll')
            zipf.write('./Magitek/bin/release/Version.txt', arcname='Version.txt')
            zipf.write('./MagitekLoader/MagitekLoader.cs', arcname='MagitekLoader.cs')
            zipf.write('./Magitek/Properties/AssemblyInfo.cs', arcname='Properties/AssemblyInfo.cs')
        "

    - name: Upload Artifacts for Release
      uses: actions/upload-artifact@v4
      with:
        name: Magitek.zip
        path: ./Magitek/bin/release/Magitek.zip

    - name: Upload Version.txt for Release
      uses: actions/upload-artifact@v4
      with:
        name: Version.txt
        path: ./Magitek/bin/release/Version.txt
